export const CROATIAN_COUNTIES = [
  'Bjelovarsko-bilogorska županija',
  'Brodsko-posavska županija',
  'Dubrovačko-neretvanska županija',
  'Grad Zagreb',
  'Istarska županija',
  'Karlovačka županija',
  'Koprivničko-križevačka županija',
  'Krapinsko-zagorska županija',
  'Ličko-senjska županija',
  'Međimurska županija',
  'Osječko-baranjska županija',
  'Požeško-slavonska županija',
  'Primorsko-goranska županija',
  'Sisačko-moslavačka županija',
  'Splitsko-dalmatinska županija',
  'Šibensko-kninska županija',
  'Varaždinska županija',
  'Virovitičko-podravska županija',
  'Vukovarsko-srijemska županija',
  'Zadarska županija',
  'Zagrebačka županija',
] as const;
