# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Pull request validator

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }},
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }},
      NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }},
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run linter
        run: yarn lint

      - name: Run formatter
        run: yarn prettier:check
